
target 'MessengerApp' do
  use_frameworks!
  platform :ios, '18.0'

  pod 'BlackBerryDynamics'

end

target 'MessengerWatchApp' do
  use_frameworks!
  platform :ios, '18.0'

  pod 'BlackBerryDynamics'

end
