# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Basic Swift Sample' do
  pod 'SQLite.swift', '~> 0.12.0'
  # Comment the next line if you don't want to use dynamic frameworks
 # use_frameworks!

  # Pods for Basic Swift Sample

end
